// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimInviteByHash = `-- name: ClaimInviteByHash :one
UPDATE invites SET used_at = NOW(), updated_at = NOW()
WHERE code_hash = $1
  AND used_at IS NULL AND deleted_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
RETURNING id, code_hash, note, expires_at, used_at, api_key_id, created_at, updated_at, deleted_at
`

// Marks an invite used in one UPDATE, so two redemptions racing the same
// code cannot both succeed.
func (q *Queries) ClaimInviteByHash(ctx context.Context, codeHash string) (Invite, error) {
	row := q.db.QueryRow(ctx, claimInviteByHash, codeHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Note,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.ApiKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (id, code_hash, note, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, code_hash, note, expires_at, used_at, api_key_id, created_at, updated_at, deleted_at
`

type CreateInviteParams struct {
	ID        string             `json:"id"`
	CodeHash  string             `json:"code_hash"`
	Note      string             `json:"note"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.CodeHash,
		arg.Note,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Note,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.ApiKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :execrows
UPDATE invites SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND used_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) DeleteInvite(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveInvites = `-- name: ListActiveInvites :many
SELECT id, code_hash, note, expires_at, used_at, api_key_id, created_at, updated_at, deleted_at FROM invites
WHERE used_at IS NULL AND deleted_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

// Unused, unexpired, undeleted invites.
func (q *Queries) ListActiveInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listActiveInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.Note,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.ApiKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInviteKey = `-- name: SetInviteKey :exec
UPDATE invites SET api_key_id = $2, updated_at = NOW()
WHERE id = $1
`

type SetInviteKeyParams struct {
	ID       string  `json:"id"`
	ApiKeyID *string `json:"api_key_id"`
}

func (q *Queries) SetInviteKey(ctx context.Context, arg SetInviteKeyParams) error {
	_, err := q.db.Exec(ctx, setInviteKey, arg.ID, arg.ApiKeyID)
	return err
}
