// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Invite struct {
	ID        string             `json:"id"`
	CodeHash  string             `json:"code_hash"`
	Note      string             `json:"note"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	ApiKeyID  *string            `json:"api_key_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type OauthClient struct {
	ID           string             `json:"id"`
	RedirectUris []byte             `json:"redirect_uris"`
	ClientName   *string            `json:"client_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type OauthCode struct {
	CodeHash            string             `json:"code_hash"`
	ClientID            string             `json:"client_id"`
	ApiKeyID            string             `json:"api_key_id"`
	RedirectUri         string             `json:"redirect_uri"`
	CodeChallenge       string             `json:"code_challenge"`
	CodeChallengeMethod string             `json:"code_challenge_method"`
	Scope               *string            `json:"scope"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type OauthToken struct {
	ID               string             `json:"id"`
	TokenHash        string             `json:"token_hash"`
	ClientID         *string            `json:"client_id"`
	ApiKeyID         string             `json:"api_key_id"`
	Scope            *string            `json:"scope"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RefreshTokenHash *string            `json:"refresh_token_hash"`
	RefreshExpiresAt pgtype.Timestamptz `json:"refresh_expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Species struct {
	ID                  string             `json:"id"`
	Seed                int64              `json:"seed"`
	GeneratorRev        string             `json:"generator_rev"`
	Singular            string             `json:"singular"`
	Plural              string             `json:"plural"`
	ScientificName      string             `json:"scientific_name"`
	Emoji               string             `json:"emoji"`
	Temperament         string             `json:"temperament"`
	FormCount           int32              `json:"form_count"`
	Description         string             `json:"description"`
	Data                []byte             `json:"data"`
	Notes               string             `json:"notes"`
	CreatedBy           *string            `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DescriptionOverride string             `json:"description_override"`
}

type SpriteCandidate struct {
	ID         string             `json:"id"`
	SpeciesID  string             `json:"species_id"`
	Form       int32              `json:"form"`
	Svg        string             `json:"svg"`
	Note       string             `json:"note"`
	Author     string             `json:"author"`
	CreatedBy  *string            `json:"created_by"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}
