// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOAuthCode = `-- name: ConsumeOAuthCode :one
UPDATE oauth_codes SET consumed_at = NOW()
WHERE code_hash = $1 AND consumed_at IS NULL AND expires_at > NOW()
RETURNING code_hash, client_id, api_key_id, redirect_uri, code_challenge, code_challenge_method, scope, expires_at, consumed_at, created_at
`

func (q *Queries) ConsumeOAuthCode(ctx context.Context, codeHash string) (OauthCode, error) {
	row := q.db.QueryRow(ctx, consumeOAuthCode, codeHash)
	var i OauthCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.ApiKeyID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Scope,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (id, redirect_uris, client_name)
VALUES ($1, $2, $3)
RETURNING id, redirect_uris, client_name, created_at, deleted_at
`

type CreateOAuthClientParams struct {
	ID           string  `json:"id"`
	RedirectUris []byte  `json:"redirect_uris"`
	ClientName   *string `json:"client_name"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient, arg.ID, arg.RedirectUris, arg.ClientName)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.RedirectUris,
		&i.ClientName,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createOAuthCode = `-- name: CreateOAuthCode :exec
INSERT INTO oauth_codes (
    code_hash, client_id, api_key_id, redirect_uri,
    code_challenge, code_challenge_method, scope, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateOAuthCodeParams struct {
	CodeHash            string             `json:"code_hash"`
	ClientID            string             `json:"client_id"`
	ApiKeyID            string             `json:"api_key_id"`
	RedirectUri         string             `json:"redirect_uri"`
	CodeChallenge       string             `json:"code_challenge"`
	CodeChallengeMethod string             `json:"code_challenge_method"`
	Scope               *string            `json:"scope"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuthCode(ctx context.Context, arg CreateOAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createOAuthCode,
		arg.CodeHash,
		arg.ClientID,
		arg.ApiKeyID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Scope,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthToken = `-- name: CreateOAuthToken :exec
INSERT INTO oauth_tokens (
    id, token_hash, client_id, api_key_id, scope, expires_at,
    refresh_token_hash, refresh_expires_at
) VALUES (
    $1, $2, $6, $3, $4, $5,
    $7, $8
)
`

type CreateOAuthTokenParams struct {
	ID               string             `json:"id"`
	TokenHash        string             `json:"token_hash"`
	ApiKeyID         string             `json:"api_key_id"`
	Scope            *string            `json:"scope"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ClientID         *string            `json:"client_id"`
	RefreshTokenHash *string            `json:"refresh_token_hash"`
	RefreshExpiresAt pgtype.Timestamptz `json:"refresh_expires_at"`
}

func (q *Queries) CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, createOAuthToken,
		arg.ID,
		arg.TokenHash,
		arg.ApiKeyID,
		arg.Scope,
		arg.ExpiresAt,
		arg.ClientID,
		arg.RefreshTokenHash,
		arg.RefreshExpiresAt,
	)
	return err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, redirect_uris, client_name, created_at, deleted_at FROM oauth_clients
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOAuthClient(ctx context.Context, id string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.RedirectUris,
		&i.ClientName,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOAuthTokenByHash = `-- name: GetOAuthTokenByHash :one
SELECT oauth_tokens.id, oauth_tokens.token_hash, oauth_tokens.client_id, oauth_tokens.api_key_id, oauth_tokens.scope, oauth_tokens.expires_at, oauth_tokens.refresh_token_hash, oauth_tokens.refresh_expires_at, oauth_tokens.revoked_at, oauth_tokens.created_at FROM oauth_tokens
JOIN api_keys ON api_keys.id = oauth_tokens.api_key_id AND api_keys.deleted_at IS NULL
WHERE token_hash = $1
  AND oauth_tokens.revoked_at IS NULL
  AND oauth_tokens.expires_at > NOW()
`

// A token stops working when its api key is deleted.
func (q *Queries) GetOAuthTokenByHash(ctx context.Context, tokenHash string) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthTokenByHash, tokenHash)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ClientID,
		&i.ApiKeyID,
		&i.Scope,
		&i.ExpiresAt,
		&i.RefreshTokenHash,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthTokenByRefreshHash = `-- name: GetOAuthTokenByRefreshHash :one
SELECT oauth_tokens.id, oauth_tokens.token_hash, oauth_tokens.client_id, oauth_tokens.api_key_id, oauth_tokens.scope, oauth_tokens.expires_at, oauth_tokens.refresh_token_hash, oauth_tokens.refresh_expires_at, oauth_tokens.revoked_at, oauth_tokens.created_at FROM oauth_tokens
JOIN api_keys ON api_keys.id = oauth_tokens.api_key_id AND api_keys.deleted_at IS NULL
WHERE refresh_token_hash = $1
  AND oauth_tokens.revoked_at IS NULL
  AND oauth_tokens.refresh_expires_at > NOW()
`

func (q *Queries) GetOAuthTokenByRefreshHash(ctx context.Context, refreshTokenHash *string) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthTokenByRefreshHash, refreshTokenHash)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ClientID,
		&i.ApiKeyID,
		&i.Scope,
		&i.ExpiresAt,
		&i.RefreshTokenHash,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeOAuthToken = `-- name: RevokeOAuthToken :exec
UPDATE oauth_tokens SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeOAuthToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeOAuthToken, id)
	return err
}

const revokeOAuthTokenByHash = `-- name: RevokeOAuthTokenByHash :exec
UPDATE oauth_tokens SET revoked_at = NOW()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeOAuthTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeOAuthTokenByHash, tokenHash)
	return err
}
