// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: species.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpecies = `-- name: CreateSpecies :one
INSERT INTO species (
    id, seed, generator_rev, singular, plural, scientific_name, emoji,
    temperament, form_count, description, data, notes, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, seed, generator_rev, singular, plural, scientific_name, emoji, temperament, form_count, description, data, notes, created_by, created_at, updated_at, deleted_at, description_override
`

type CreateSpeciesParams struct {
	ID             string  `json:"id"`
	Seed           int64   `json:"seed"`
	GeneratorRev   string  `json:"generator_rev"`
	Singular       string  `json:"singular"`
	Plural         string  `json:"plural"`
	ScientificName string  `json:"scientific_name"`
	Emoji          string  `json:"emoji"`
	Temperament    string  `json:"temperament"`
	FormCount      int32   `json:"form_count"`
	Description    string  `json:"description"`
	Data           []byte  `json:"data"`
	Notes          string  `json:"notes"`
	CreatedBy      *string `json:"created_by"`
}

func (q *Queries) CreateSpecies(ctx context.Context, arg CreateSpeciesParams) (Species, error) {
	row := q.db.QueryRow(ctx, createSpecies,
		arg.ID,
		arg.Seed,
		arg.GeneratorRev,
		arg.Singular,
		arg.Plural,
		arg.ScientificName,
		arg.Emoji,
		arg.Temperament,
		arg.FormCount,
		arg.Description,
		arg.Data,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.Seed,
		&i.GeneratorRev,
		&i.Singular,
		&i.Plural,
		&i.ScientificName,
		&i.Emoji,
		&i.Temperament,
		&i.FormCount,
		&i.Description,
		&i.Data,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DescriptionOverride,
	)
	return i, err
}

const deleteSpecies = `-- name: DeleteSpecies :execrows
UPDATE species SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteSpecies(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpecies, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSpecies = `-- name: GetSpecies :one
SELECT id, seed, generator_rev, singular, plural, scientific_name, emoji, temperament, form_count, description, data, notes, created_by, created_at, updated_at, deleted_at, description_override FROM species
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSpecies(ctx context.Context, id string) (Species, error) {
	row := q.db.QueryRow(ctx, getSpecies, id)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.Seed,
		&i.GeneratorRev,
		&i.Singular,
		&i.Plural,
		&i.ScientificName,
		&i.Emoji,
		&i.Temperament,
		&i.FormCount,
		&i.Description,
		&i.Data,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DescriptionOverride,
	)
	return i, err
}

const listSpecies = `-- name: ListSpecies :many
SELECT species.id, species.seed, species.generator_rev, species.singular, species.plural, species.scientific_name, species.emoji, species.temperament, species.form_count, species.description, species.data, species.notes, species.created_by, species.created_at, species.updated_at, species.deleted_at, species.description_override,
       (SELECT COUNT(*) FROM sprite_candidates c
         WHERE c.species_id = species.id AND c.accepted_at IS NOT NULL
           AND c.deleted_at IS NULL)::INT AS accepted_count
FROM species
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

type ListSpeciesRow struct {
	ID                  string             `json:"id"`
	Seed                int64              `json:"seed"`
	GeneratorRev        string             `json:"generator_rev"`
	Singular            string             `json:"singular"`
	Plural              string             `json:"plural"`
	ScientificName      string             `json:"scientific_name"`
	Emoji               string             `json:"emoji"`
	Temperament         string             `json:"temperament"`
	FormCount           int32              `json:"form_count"`
	Description         string             `json:"description"`
	Data                []byte             `json:"data"`
	Notes               string             `json:"notes"`
	CreatedBy           *string            `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DescriptionOverride string             `json:"description_override"`
	AcceptedCount       int32              `json:"accepted_count"`
}

// Newest first, with how many of each species' slots have an accepted sprite.
func (q *Queries) ListSpecies(ctx context.Context) ([]ListSpeciesRow, error) {
	rows, err := q.db.Query(ctx, listSpecies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpeciesRow{}
	for rows.Next() {
		var i ListSpeciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Seed,
			&i.GeneratorRev,
			&i.Singular,
			&i.Plural,
			&i.ScientificName,
			&i.Emoji,
			&i.Temperament,
			&i.FormCount,
			&i.Description,
			&i.Data,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DescriptionOverride,
			&i.AcceptedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpecies = `-- name: UpdateSpecies :one
UPDATE species SET
    notes = COALESCE($2, notes),
    description_override = COALESCE($3, description_override),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, seed, generator_rev, singular, plural, scientific_name, emoji, temperament, form_count, description, data, notes, created_by, created_at, updated_at, deleted_at, description_override
`

type UpdateSpeciesParams struct {
	ID                  string  `json:"id"`
	Notes               *string `json:"notes"`
	DescriptionOverride *string `json:"description_override"`
}

// Sets whichever of notes and description_override are given (non-null)
// and leaves the other alone. An empty description_override resets the
// field notes to the generated text.
func (q *Queries) UpdateSpecies(ctx context.Context, arg UpdateSpeciesParams) (Species, error) {
	row := q.db.QueryRow(ctx, updateSpecies, arg.ID, arg.Notes, arg.DescriptionOverride)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.Seed,
		&i.GeneratorRev,
		&i.Singular,
		&i.Plural,
		&i.ScientificName,
		&i.Emoji,
		&i.Temperament,
		&i.FormCount,
		&i.Description,
		&i.Data,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DescriptionOverride,
	)
	return i, err
}
