// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sprites.sql

package db

import (
	"context"
)

const clearAccepted = `-- name: ClearAccepted :exec
UPDATE sprite_candidates SET accepted_at = NULL, updated_at = NOW()
WHERE species_id = $1 AND form = $2 AND accepted_at IS NOT NULL AND deleted_at IS NULL
`

type ClearAcceptedParams struct {
	SpeciesID string `json:"species_id"`
	Form      int32  `json:"form"`
}

func (q *Queries) ClearAccepted(ctx context.Context, arg ClearAcceptedParams) error {
	_, err := q.db.Exec(ctx, clearAccepted, arg.SpeciesID, arg.Form)
	return err
}

const createCandidate = `-- name: CreateCandidate :one
INSERT INTO sprite_candidates (id, species_id, form, svg, note, author, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, species_id, form, svg, note, author, created_by, accepted_at, created_at, updated_at, deleted_at
`

type CreateCandidateParams struct {
	ID        string  `json:"id"`
	SpeciesID string  `json:"species_id"`
	Form      int32   `json:"form"`
	Svg       string  `json:"svg"`
	Note      string  `json:"note"`
	Author    string  `json:"author"`
	CreatedBy *string `json:"created_by"`
}

func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) (SpriteCandidate, error) {
	row := q.db.QueryRow(ctx, createCandidate,
		arg.ID,
		arg.SpeciesID,
		arg.Form,
		arg.Svg,
		arg.Note,
		arg.Author,
		arg.CreatedBy,
	)
	var i SpriteCandidate
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.Form,
		&i.Svg,
		&i.Note,
		&i.Author,
		&i.CreatedBy,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCandidate = `-- name: DeleteCandidate :execrows
UPDATE sprite_candidates SET deleted_at = NOW(), updated_at = NOW(), accepted_at = NULL
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteCandidate(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCandidate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCandidate = `-- name: GetCandidate :one
SELECT id, species_id, form, svg, note, author, created_by, accepted_at, created_at, updated_at, deleted_at FROM sprite_candidates
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCandidate(ctx context.Context, id string) (SpriteCandidate, error) {
	row := q.db.QueryRow(ctx, getCandidate, id)
	var i SpriteCandidate
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.Form,
		&i.Svg,
		&i.Note,
		&i.Author,
		&i.CreatedBy,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAcceptedForSpecies = `-- name: ListAcceptedForSpecies :many
SELECT id, species_id, form, svg, note, author, created_by, accepted_at, created_at, updated_at, deleted_at FROM sprite_candidates
WHERE species_id = $1 AND accepted_at IS NOT NULL AND deleted_at IS NULL
ORDER BY form
`

func (q *Queries) ListAcceptedForSpecies(ctx context.Context, speciesID string) ([]SpriteCandidate, error) {
	rows, err := q.db.Query(ctx, listAcceptedForSpecies, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpriteCandidate{}
	for rows.Next() {
		var i SpriteCandidate
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.Form,
			&i.Svg,
			&i.Note,
			&i.Author,
			&i.CreatedBy,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccepted = `-- name: ListAllAccepted :many
SELECT sprite_candidates.id, sprite_candidates.species_id, sprite_candidates.form, sprite_candidates.svg, sprite_candidates.note, sprite_candidates.author, sprite_candidates.created_by, sprite_candidates.accepted_at, sprite_candidates.created_at, sprite_candidates.updated_at, sprite_candidates.deleted_at FROM sprite_candidates
JOIN species ON species.id = sprite_candidates.species_id AND species.deleted_at IS NULL
WHERE sprite_candidates.accepted_at IS NOT NULL AND sprite_candidates.deleted_at IS NULL
ORDER BY sprite_candidates.species_id, sprite_candidates.form
`

// Every accepted sprite of every live species, for the export.
func (q *Queries) ListAllAccepted(ctx context.Context) ([]SpriteCandidate, error) {
	rows, err := q.db.Query(ctx, listAllAccepted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpriteCandidate{}
	for rows.Next() {
		var i SpriteCandidate
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.Form,
			&i.Svg,
			&i.Note,
			&i.Author,
			&i.CreatedBy,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandidates = `-- name: ListCandidates :many
SELECT id, species_id, form, svg, note, author, created_by, accepted_at, created_at, updated_at, deleted_at FROM sprite_candidates
WHERE species_id = $1 AND deleted_at IS NULL
ORDER BY form, created_at DESC
`

// Every live candidate for a species, newest first within each form.
func (q *Queries) ListCandidates(ctx context.Context, speciesID string) ([]SpriteCandidate, error) {
	rows, err := q.db.Query(ctx, listCandidates, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpriteCandidate{}
	for rows.Next() {
		var i SpriteCandidate
		if err := rows.Scan(
			&i.ID,
			&i.SpeciesID,
			&i.Form,
			&i.Svg,
			&i.Note,
			&i.Author,
			&i.CreatedBy,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccepted = `-- name: MarkAccepted :one
UPDATE sprite_candidates SET accepted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, species_id, form, svg, note, author, created_by, accepted_at, created_at, updated_at, deleted_at
`

func (q *Queries) MarkAccepted(ctx context.Context, id string) (SpriteCandidate, error) {
	row := q.db.QueryRow(ctx, markAccepted, id)
	var i SpriteCandidate
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.Form,
		&i.Svg,
		&i.Note,
		&i.Author,
		&i.CreatedBy,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
